version: '3.8'

services:
  file-station:
    build: .
    container_name: flask_file_transfer
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads  # 将宿主机的 uploads 文件夹映射到容器内
    restart: always